/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccore_nfcjni_NFCJni */

#ifndef _Included_com_ccore_nfcjni_NFCJni
#define _Included_com_ccore_nfcjni_NFCJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EnumDev
 * Signature: (Z[C)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EnumDev
  (JNIEnv *, jobject, jboolean, jcharArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ConnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ConnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GetDevInfo
 * Signature: (Lcom/ccore/nfcjni/SKFType/DEVINFO;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GetDevInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GetFileInfo
 * Signature: (Ljava/lang/String;Lcom/ccore/nfcjni/SKFType/FILEATTRIBUTE;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GetFileInfo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DisconnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DisconnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_SetAppPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1SetAppPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_SetSymmKey
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1SetSymmKey
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EncryptInit
 * Signature: (Lcom/ccore/nfcjni/SKFType/BLOCKCIPHERPARAM;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EncryptInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_Encrypt
 * Signature: ([BJ[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1Encrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EncryptUpdate
 * Signature: ([BJ[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EncryptUpdate
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EncryptFinal
 * Signature: ([B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EncryptFinal
  (JNIEnv *, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DecryptInit
 * Signature: (Lcom/ccore/nfcjni/SKFType/BLOCKCIPHERPARAM;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DecryptInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_Decrypt
 * Signature: ([BJ[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1Decrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DecryptUpdate
 * Signature: ([BJ[B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DecryptUpdate
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DecryptFinal
 * Signature: ([B[J)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DecryptFinal
  (JNIEnv *, jobject, jbyteArray, jlongArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GetDevState
 * Signature: (Ljava/lang/String;Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GetDevState
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_SetLabel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1SetLabel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_LockDev
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1LockDev
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_UnlockDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1UnlockDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_Transmit
 * Signature: ([BJ[BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1Transmit
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ChangeDevAuthKey
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ChangeDevAuthKey
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DevAuth
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DevAuth
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ChangePIN
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ChangePIN
  (JNIEnv *, jobject, jint, jstring, jstring, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GetPINInfo
 * Signature: (ILjava/lang/Integer;Ljava/lang/Integer;[Z)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GetPINInfo
  (JNIEnv *, jobject, jint, jobject, jobject, jbooleanArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_VerifyPIN
 * Signature: (ILjava/lang/String;Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1VerifyPIN
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_UnblockPIN
 * Signature: ([BLjava/lang/String;Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1UnblockPIN
  (JNIEnv *, jobject, jbyteArray, jstring, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ClearSecureState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ClearSecureState
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_CreateApplication
 * Signature: ([B[BJ[BJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1CreateApplication
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jlong, jbyteArray, jlong, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EnumApplication
 * Signature: ([BLjava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EnumApplication
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DeleteApplication
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DeleteApplication
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_OpenApplication
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1OpenApplication
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_CloseApplication
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1CloseApplication
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_CreateFile
 * Signature: ([BJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1CreateFile
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DeleteFile
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DeleteFile
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EnumFiles
 * Signature: ([BLjava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EnumFiles
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ReadFile
 * Signature: ([BJJ[BLjava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ReadFile
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jbyteArray, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_WriteFile
 * Signature: ([BJ[BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1WriteFile
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_CreateContainer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1CreateContainer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_DeleteContainer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1DeleteContainer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_OpenContainer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1OpenContainer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_CloseContainer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1CloseContainer
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_EnumContainer
 * Signature: ([BLjava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1EnumContainer
  (JNIEnv *, jobject, jbyteArray, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GetContainerType
 * Signature: (Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GetContainerType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GenRandom
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GenRandom
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GenExtRSAKey
 * Signature: (ILcom/ccore/nfcjni/SKFType/RSAPRIVATEKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GenExtRSAKey
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_GenRSAKeyPair
 * Signature: (ILcom/ccore/nfcjni/SKFType/RSAPRIVATEKEYBLOB;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1GenRSAKeyPair
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_ImportRSAKeyPair
 * Signature: (I[BI[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1ImportRSAKeyPair
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_RSASignData
 * Signature: ([BI[BLjava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1RSASignData
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    SKF_RSAVerify
 * Signature: (Lcom/ccore/nfcjni/SKFType/RSAPUBLICKEYBLOB;[BI[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_SKF_1RSAVerify
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    NFC_GenRandom
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_NFC_1GenRandom
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    NFC_GetDevInfo
 * Signature: (Lcom/ccore/nfcjni/SKFType/DEVINFO;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_NFC_1GetDevInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    transmitJni
 * Signature: ([BI[B[I)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_transmitJni
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jintArray);

/*
 * Class:     com_ccore_nfcjni_NFCJni
 * Method:    V_SetNFC_Class
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_nfcjni_NFCJni_V_1SetNFC_1Class
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
