
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ccore_jni_SKFJni */

#ifndef _Included_com_ccore_jni_SKFJni
#define _Included_com_ccore_jni_SKFJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_EnumDev
 * Signature: (Z[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1EnumDev
  (JNIEnv *, jobject, jboolean, jbyteArray);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_ConnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1ConnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_GetDevInfo
 * Signature: (Lcom/ccore/jni/SKFType/DEVINFO;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1GetDevInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_GetFileInfo
 * Signature: (Ljava/lang/String;Lcom/ccore/jni/SKFType/FILEATTRIBUTE;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1GetFileInfo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_DisconnectDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1DisconnectDev
  (JNIEnv *, jobject);

/*
 * Class:     com_ccore_jni_SKFJni
 * Method:    SKF_SetAppPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ccore_jni_SKFJni_SKF_1SetAppPath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
